# Conda channels. We recommend using packages from the conda-forge channel.
channels:
  - conda-forge
dependencies:
  # Defining conda packages:
  - python=3.7.5
  # Adding pip itself as a conda package:
  - pip=20.1
  - pip:
      # Defining pip packages:
      - smtplib
      - DateTime
      - python-decouple
      - email
      - selenium
      - retry
      - python-time
      - beautifulsoup4
      - rpaframework==14.0.0